### ISSUE TITLE
Chests not generating loot correctly while AbnormalsCore is installed - mod conflict

### ISSUE THREAD

**Issue by katubug** [minecraftabnormals/Abnormals-Core#14]
Hi, I've been having an issue both in singleplayer and on my server wherein certain chests are randomly spawning as completely empty. The chest most reliably affected by this bug is the Buried Treasure, although it also happens to other vanilla chests sporadically such as Desert Temples, and modded structure chests as well.

I believe the issue is a mod conflict between Abnormals Core and other mods. One mod I know for certain is conflicting is Bound Totems. However, even with Bound Totems removed from my instance, the issue still persists. Two mods that I have reliably replicated this with are Upgrade Aquatic and Endergetic Expansion. However, I believe the issue is potentially with any/all mods that use AbnormalsCore, because simply removing EE and UA from my primary instance does not fix the issue.

I took a fair amount of notes while I was testing things, which can be found here: https://pastebin.com/tPGF9gUJ

Throughout all of this, there is not much in the latest.log, but I can provide you log files if you think it'll help.

Here are my versions (basically everything is the latest as of 7/18) - 

**Minecraft: 1.15.2
Abnormals Core: 1.0.6
Bound Totems: 1.3.0
Forge: 31.2.31**

The modpack version I am using is here, but if you want, I can print you a list of all my mod filenames: https://www.curseforge.com/minecraft/modpacks/rustic-wanderings/files/3008756

Please let me know if there's anything else I can do to help! I love your mods and would love to pin down this incredibly frustrating issue. :)

**Comment by bageldotjpg** [comment]
You'll need to replicate specifically what mod does it.
- Try in a separate instance with only Abnormals Core -> if it is filled, its not Abnormals Core's fault
- Try with just AC and Upgrade Aquatic -> if it is filled, its not Upgrade Aquatic's fault
- etc. etc. 
Your method feels very convoluted and hard to keep track of or narrow anything down. It would also be great if you posted a log for us to examine as well 👍

**Comment by katubug** [comment]
I know it is not Abnormals Core or UA by itself, but a conflict between them and at least one other mod. The mod I've been testing with is Bound Totems, however there is at least one other such mod in my primary modlist. I apologize for the scattered nature of my notes. I suffer from some cognitive difficulties, but I have tried to make things as clear as I can.

In an instance with only these mods:
- Forge 31.2.31
- Abnormals Core 1.0.6
- Bound Totems 1.3.0
- Upgrade Aquatic 1.7.1

I loaded up the game, created a fresh singleplayer world, did /locate to find a Buried Treasure, and teleported to it. I dug down to it, opened it to find it empty, said "empty chest" in the log, and then saved and exited to title. Here is the log: https://paste.ee/p/5ra7H

In the same instance, if I disable either Upgrade Aquatic or Bound Totems, the issue does not occur.

**Comment by katubug** [comment]
Oh, and here is a latest.log from my server - https://paste.ee/p/JeKpq

**Comment by katubug** [comment]
Also, let me know if I should move this ticket elsewhere, or report it to someone else.

**Comment by katubug** [comment]
Likely related - https://github.com/Phylogeny/BoundTotems/issues/4

**Comment by SmellyModder** [comment]
This commit appears to have fixed it and was an issue on Bound Totems' side. https://github.com/Phylogeny/BoundTotems/commit/f1145b2f23844f6c4925be7e90a32f5110bceebe
