### ISSUE TITLE
java.lang.ClassNotFoundException with buzzier bees on latest version

### ISSUE THREAD

**Issue by PssbleTrngle** [minecraftabnormals/Abnormals-Core#15]
Updating to the latest version of abnormals core (1.16.1-v2.1.0) caused buzzier bees to throw
```java
java.lang.ClassNotFoundException: com.teamabnormals.abnormals_core.core.utils.RegistryHelper
```

[Crash Report](https://paste.gg/p/anonymous/0bb69f79a7a545c4955c7b01a9105f39)
Forge Version: 32.0.93
Buzzier Bees: 1.16.1-2.0.0
Abnormals Core: 1.16.1-v2.1.0

**Comment by bageldotjpg** [comment]
Re-install latest Abnormals Core, this should be fixed. Sorry for the inconvience.
