### ISSUE TITLE
[1.16] Possible Conflict with Just Enough Resources

### ISSUE THREAD

**Issue by NillerMedDild** [minecraftabnormals/Abnormals-Core#16]
Just Enough Resources adds a JEI tab for mob drops, which gets removed completely if Abnormals Core and Buzzier Bees is also in the instance.

Here's the relevant error in the latest.log: https://gist.github.com/NillerMedDild/d687e2a0529732e91a8699c7364d8a4d

Related issue: https://github.com/way2muchnoise/JustEnoughResources/issues/247

**Comment by SmellyModder** [comment]
This appears to be on Buzzier Bees' side. Open an issue there: https://github.com/minecraftabnormals/Buzzier-Bees/issues/new
