### ISSUE TITLE
Abnormals Core encountered an error during the common_setup event phase: null

### ISSUE THREAD

**Issue by NillerMedDild** [minecraftabnormals/Abnormals-Core#19]
Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/208

Mod version: `Abnormals-Core-1.16.1-2.0.3`

**Issue**
The game failed to launch.  Before it reached the main menu, it died with this error:

![image](https://user-images.githubusercontent.com/50254/91638905-bbbea100-e9e0-11ea-8c30-e2d0c1c4b787.png)

I have seen this happen exactly once.  I have been able to launch this version 4 or 5 times so far with no other issues.

**Logs**
https://paste.ee/p/CGa3S#s=0&l=852

The exception occurs on line 852.

**Comment by SmellyModder** [comment]
Ah yep this a bug.
This happens since multiple mods are modifying the POI field concurrently.
I'll make a fix for this later today 👍

**Comment by NillerMedDild** [comment]
Thank you :D
