### ISSUE TITLE
Game Crashes when trying to destroy entity

### ISSUE THREAD

**Issue by Rayskiz** [minecraftabnormals/Abnormals-Core#26]
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: com.teamabnormals.abnormals_core.common.entity.AbnormalsBoatEntity cannot be cast to net.minecraft.entity.LivingEntity
Exit Code: -1

Admitted newb, not sure what this means

https://pastebin.com/my8CyAQ0

**Comment by bageldotjpg** [comment]
I don't know why, but the "Endorite" mod is doing something weird that they shouldn't be doing, I'd recommend reporting it to them.
