### ISSUE TITLE
Sign textures broken

### ISSUE THREAD

**Issue by Epic312** [minecraftabnormals/Abnormals-Core#30]
Using MCA mods it looks like signs are using the wrong textures as of 2.0.5. The texture used varies each time the game starts up and sometimes is just a missing texture, but all AC signs use the same texture.

To reproduce just drop a few MCA mods in that have wood sets and place a couple different types down.

[Here's a screenshot of Grimwood looking like Maple.](https://media.discordapp.net/attachments/729290806493708290/764942623315722250/unknown.png?width=379&height=677)

**Comment by Epic312** [comment]
Worth mentioning that this happens **whenever two or more AC signs are present.** This means even just installing one mod with multiple wood types (e.g. UA, Atmospheric, EM) causes this issue.

Seems like most of the time the first sign placed is the texture they all end up using. Strange.

**Comment by Epic312** [comment]
WAIT SHIT I CLOSED IT

**Comment by bageldotjpg** [comment]
@JacksonPlayz :sadcat: whatd u do

**Comment by SmellyModder** [comment]
@JacksonPlayz 🅰️

**Comment by Epic312** [comment]
You guys forgot to close it lol
