### ISSUE TITLE
[1.15.2] Missing data fixer for `abnormals_core:boat`

### ISSUE THREAD

**Issue by jrkulmer** [minecraftabnormals/Abnormals-Core#8]
```[27May2020 00:15:43.871] [Render thread/WARN] [net.minecraft.entity.EntityType/]: No data fixer registered for entity abnormals_core:boat```

Forge version: 3.1.20
Abnormal's Core Version: 1.0.4

**Comment by SmellyModder** [comment]
This occurs in every forge modded entity.
